// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PdsTk.Infraestructura.Persistencia;

#nullable disable

namespace PdsTk.Infraestructura.Migrations
{
    [DbContext(typeof(PdsTkDbContext))]
    partial class PdsTkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PdsTk.Dominio.Entidades.ComentarioIncidente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("EsInterno")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IncidenteId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IncidenteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ComentariosIncidente", (string)null);
                });

            modelBuilder.Entity("PdsTk.Dominio.Entidades.Incidente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("AgenteAsignadoId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaLimitePrimeraRespuesta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaLimiteResolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPrimeraRespuesta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PoliticaSLAId")
                        .HasColumnType("int");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<int>("SolicitanteId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AgenteAsignadoId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Estado");

                    b.HasIndex("PoliticaSLAId");

                    b.HasIndex("Prioridad");

                    b.HasIndex("SolicitanteId");

                    b.ToTable("Incidentes", (string)null);
                });

            modelBuilder.Entity("PdsTk.Dominio.Entidades.PoliticaSLA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TiempoPrimeraRespuestaMinutos")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("TiempoResolucionMinutos")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("PoliticaSLA", (string)null);
                });

            modelBuilder.Entity("PdsTk.Dominio.Entidades.RegistroAuditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IncidenteId")
                        .HasColumnType("int");

                    b.Property<int>("TipoAccion")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("ValorAnterior")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ValorNuevo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("IncidenteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RegistrosAuditoria", (string)null);
                });

            modelBuilder.Entity("PdsTk.Dominio.Entidades.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("PdsTk.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("PdsTk.Dominio.Entidades.ComentarioIncidente", b =>
                {
                    b.HasOne("PdsTk.Dominio.Entidades.Incidente", "Incidente")
                        .WithMany("Comentarios")
                        .HasForeignKey("IncidenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PdsTk.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("Comentarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Incidente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PdsTk.Dominio.Entidades.Incidente", b =>
                {
                    b.HasOne("PdsTk.Dominio.Entidades.Usuario", "AgenteAsignado")
                        .WithMany("IncidentesAsignados")
                        .HasForeignKey("AgenteAsignadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PdsTk.Dominio.Entidades.PoliticaSLA", "PoliticaSLA")
                        .WithMany("Incidentes")
                        .HasForeignKey("PoliticaSLAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PdsTk.Dominio.Entidades.Usuario", "Solicitante")
                        .WithMany("IncidentesSolicitados")
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgenteAsignado");

                    b.Navigation("PoliticaSLA");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("PdsTk.Dominio.Entidades.RegistroAuditoria", b =>
                {
                    b.HasOne("PdsTk.Dominio.Entidades.Incidente", "Incidente")
                        .WithMany("RegistrosAuditoria")
                        .HasForeignKey("IncidenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PdsTk.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("RegistrosAuditoria")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Incidente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PdsTk.Dominio.Entidades.Usuario", b =>
                {
                    b.HasOne("PdsTk.Dominio.Entidades.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("PdsTk.Dominio.Entidades.Incidente", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("RegistrosAuditoria");
                });

            modelBuilder.Entity("PdsTk.Dominio.Entidades.PoliticaSLA", b =>
                {
                    b.Navigation("Incidentes");
                });

            modelBuilder.Entity("PdsTk.Dominio.Entidades.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("PdsTk.Dominio.Entidades.Usuario", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("IncidentesAsignados");

                    b.Navigation("IncidentesSolicitados");

                    b.Navigation("RegistrosAuditoria");
                });
#pragma warning restore 612, 618
        }
    }
}
